name: publish

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI

    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/texifast

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python 3.11
        run: uv python install 3.11

      - name: Install the project
        run: uv sync --extra cpu --dev

      - name: Build package
        run: |
          uv run -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
